 $(document).ready(() => {

        $('.do').click(() => {
            $('.grau1').html('C')
            $('.grau2').html('Dm')
            $('.grau3').html('Em')
            $('.grau4').html('F')
            $('.grau5').html('G')
            $('.grau6').html('Am')
            $('.grau7').html('B°')
            $('.modulacao').html('E')
        })
        $('.dosus').click(() => {
            $('.grau1').html('C#')
            $('.grau2').html('Dm#')
            $('.grau3').html('Fm')
            $('.grau4').html('F#')
            $('.grau5').html('A#')
            $('.grau6').html('Bbm')
            $('.grau7').html('C°')
            $('.modulacao').html('F')
        })
        $('.re').click(() => {
            $('.grau1').html('D')
            $('.grau2').html('Em')
            $('.grau3').html('F#m')
            $('.grau4').html('G')
            $('.grau5').html('A')
            $('.grau6').html('Bm')
            $('.grau7').html('D#°')
            $('.modulacao').html('F#')
        })
        $('.mib').click(() => {
            $('.grau1').html('Eb')
            $('.grau2').html('Fm')
            $('.grau3').html('Gm')
            $('.grau4').html('Ab')
            $('.grau5').html('Bb')
            $('.grau6').html('Cm')
            $('.grau7').html('D°')
            $('.modulacao').html('G')
        })
        $('.mi').click(() => {
            $('.grau1').html('E')
            $('.grau2').html('F#m')
            $('.grau3').html('G#m')
            $('.grau4').html('A')
            $('.grau5').html('B')
            $('.grau6').html('C#m')
            $('.grau7').html('Eb°')
            $('.modulacao').html('G#')
        })
        $('.fa').click(() => {
            $('.grau1').html('F')
            $('.grau2').html('Gm')
            $('.grau3').html('Am')
            $('.grau4').html('Bb')
            $('.grau5').html('C')
            $('.grau6').html('Dm')
            $('.grau7').html('E°')
            $('.modulacao').html('A')
        })
        $('.fasus').click(() => {
            $('.grau1').html('F#')
            $('.grau2').html('G#m')
            $('.grau3').html('A#m')
            $('.grau4').html('B')
            $('.grau5').html('C#')
            $('.grau6').html('D#m')
            $('.grau7').html('F°')
            $('.modulacao').html('A#')
        })
        $('.sol').click(() => {
            $('.grau1').html('G')
            $('.grau2').html('Am')
            $('.grau3').html('Bm')
            $('.grau4').html('C')
            $('.grau5').html('D')
            $('.grau6').html('Em')
            $('.grau7').html('F#°')
            $('.modulacao').html('B')
        })
        $('.solsus').click(() => {
            $('.grau1').html('G#')
            $('.grau2').html('A#m')
            $('.grau3').html('Cm')
            $('.grau4').html('C#')
            $('.grau5').html('D#')
            $('.grau6').html('Fm')
            $('.grau7').html('G°')
            $('.modulacao').html('C')
        })
        $('.la').click(() => {
            $('.grau1').html('A')
            $('.grau2').html('Bm')
            $('.grau3').html('D#m')
            $('.grau4').html('D')
            $('.grau5').html('E')
            $('.grau6').html('F#m')
            $('.grau7').html('A°')
            $('.modulacao').html('C#')

        })
        $('.sib').click(() => {
            $('.grau1').html('Bb')
            $('.grau2').html('Cm')
            $('.grau3').html('Dm')
            $('.grau4').html('Eb')
            $('.grau5').html('F')
            $('.grau6').html('Gm')
            $('.grau7').html('B°')
            $('.modulacao').html('D')
        })
        $('.si').click(() => {
            $('.grau1').html('B')
            $('.grau2').html('C#m')
            $('.grau3').html('D#m')
            $('.grau4').html('E')
            $('.grau5').html('F#')
            $('.grau6').html('G#m')
            $('.grau7').html('Bb°')
            $('.modulacao').html('D#')
        })
          
      })

var myModal = document.getElementById('myModal')
var myInput = document.getElementById('myInput')

myModal.addEventListener('shown.bs.modal', function () {
  myInput.focus()
})